# Generated by Django 3.0.7 on 2020-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckarsSite',
            fields=[
                ('car_id', models.IntegerField(primary_key=True, serialize=False)),
                ('_id', models.CharField(max_length=50)),
                ('mlid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CheckarsSiteByID',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
                ('kilometros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeliItem',
            fields=[
                ('mlid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('precio', models.FloatField()),
                ('kilometros', models.IntegerField()),
                ('seller_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
