# Generated by Django 3.0.7 on 2020-06-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkars', '0002_auto_20200624_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeliApi',
            fields=[
                ('mlid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('seller_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='meliitem',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
